#DEFAULT RAG PARAMETERS
top_k=8
similarity=0.5
threshold_for_feature_name_similarity=0.6
longitude_column="Longitude"
latitude_column="Latitude"
risk_column="Ecosystem risk classification according to a Variational Autoencoder with a later application of a Multi K-means process"
risk_index_to_predict=2
#CHAT
chat_query_example="./query_examples/chat.txt"
chat_answer="./task_prompts/chat_answer.txt"
chat_query_similarity_threshold=0.8
#CORRELATION
correlation_query_example="./query_examples/correlation.txt"
correlation_extraction_prompt="./task_prompts/correlation_extraction.txt"
correlation_answer="./task_prompts/correlation_answer.txt"
correlation_query_similarity_threshold=0.6
#DATA
live_update_data="https://data.d4science.org/shub/E_Q005UkRYM3Z5ckRUM0hRRkpidTJBQWxXSTZTVDBRVzV5aDQxV21Sc1RpeEh1RG9Ja05sQXZFa21KaEgxRG82aQ=="
data_query_example="./query_examples/data.txt"
data_answer="./task_prompts/data_answer.txt"
data_query_similarity_threshold=0.6
#KB
knowledge_base_data="./knowledge_base_data/Massaciuccoli Lake Basin data and results for ecosystem risk assessment_VAE_only.csv"