#LLM PARAMETERS
#llm_address="localhost:11434"
llm_address="urania-ice4ai.icar.cnr.it/user/gianpaolo.coro/proxy/11434"
llm_service_type="ollama";
embedder_address="localhost:11434"
embedder_model_name="nomic-embed-text"
#llm_model="llama3.2:latest"
#llm_model="qwen3:8b"
llm_model="llama4:scout"
llm_token=""
num_ctx=16384
num_predict=500
#AGENT-SPECIFIC PARAMETERS
disclaimer="./query_examples/disclaimer.txt"
longitude_column="Longitude"
latitude_column="Latitude"
risk_column="Ecosystem risk classification according to a Variational Autoencoder with a later application of a Multi K-means process"
risk_index_to_predict=1
unknown_similarity_score=0.6
cache_folder="./cache/"
area_polygon="POLYGON ((10.285854 43.937956, 10.217885 43.897398, 10.23299 43.859287, 10.266631 43.777539, 10.311844 43.737368, 10.368142 43.77506, 10.431305 43.766135, 10.450529 43.786958, 10.46426 43.806783, 10.440917 43.822638, 10.421693 43.83948, 10.370888 43.852355, 10.285854 43.937956))"
gbif_max_samples=200
maxent_threshold_to_use="10 percentile training presence Logistic threshold"
#KB
knowledge_base_data="./knowledge_base_data/Massaciuccoli Lake Basin data and results for ecosystem risk assessment_VAE_only.csv"
#DEFAULT RAG PARAMETERS
top_k=8
similarity=0.6
threshold_for_feature_name_similarity=0.6
#CHAT
chat_query_example="./query_examples/chat.txt"
chat_answer="./task_prompts/chat_answer.txt"
chat_query_similarity_threshold=0.8
#CORRELATION
correlation_query_example="./query_examples/correlation.txt"
correlation_extraction_prompt="./task_prompts/correlation_extraction.txt"
correlation_answer="./task_prompts/correlation_answer.txt"
correlation_query_similarity_threshold=0.6
#DATA
live_update_data="https://data.d4science.org/shub/E_Q005UkRYM3Z5ckRUM0hRRkpidTJBQWxXSTZTVDBRVzV5aDQxV21Sc1RpeEh1RG9Ja05sQXZFa21KaEgxRG82aQ=="
data_query_example="./query_examples/data.txt"
data_answer="./task_prompts/data_answer.txt"
data_query_similarity_threshold=0.6
#RISK IMPORTANCE
risk_importance_query_example="./query_examples/risk_importance.txt"
risk_importance_answer="./task_prompts/risk_importance_answer.txt"
risk_importance_query_similarity_threshold=0.6
#RISK VARIATION
risk_variation_query_example="./query_examples/risk_variation.txt"
risk_variation_extraction_prompt="./task_prompts/risk_variation_extraction.txt"
risk_variation_answer="./task_prompts/risk_variation_answer.txt"
risk_variation_query_similarity_threshold=0.6
#RISK COMPARISON
risk_comparison_query_example="./query_examples/risk_comparison.txt"
risk_comparison_extraction_prompt="./task_prompts/risk_comparison_extraction.txt"
risk_comparison_answer="./task_prompts/risk_comparison_answer.txt"
risk_comparison_query_similarity_threshold=0.6
#ENM
enm_query_example="./query_examples/enm.txt"
enm_extraction_prompt="./task_prompts/enm_extraction.txt"
enm_answer="./task_prompts/enm_answer.txt"
enm_query_similarity_threshold=0.6