#DEFAULT RAG PARAMETERS
top_k=8
similarity=0.4
live_update_data="https://data.d4science.org/shub/E_Q005UkRYM3Z5ckRUM0hRRkpidTJBQWxXSTZTVDBRVzV5aDQxV21Sc1RpeEh1RG9Ja05sQXZFa21KaEgxRG82aQ=="
knowledge_base_data="./knowledge_base_data/Massaciuccoli Lake Basin data and results for ecosystem risk assessment_VAE_only.csv"